### ISSUE TITLE
Background Image for Header

### ISSUE THREAD

**Issue by adamlewinter** [CRREL/atlas.lidar.io#6]
If possible, place the attached image in the background behind the page header...magically?
![_wis1462](https://user-images.githubusercontent.com/1220647/30118495-2b6cce72-92f1-11e7-88ca-a990bebfc015.jpeg)

**Comment by gadomski** [comment]
Because the header is much wider than it is tall, just plopping the image into the grey header doesn't work so goodly:

<img width="1954" alt="screen shot 2017-09-06 at 11 34 43" src="https://user-images.githubusercontent.com/58314/30125951-75841a0a-92f7-11e7-8f8b-f8bc16e21c91.png">

Ideas on what you'd like to see?
